[package]
authors = ["hatoo <hato2000@gmail.com>"]
categories = ["command-line-utilities", "network-programming", "web-programming::http-client", "development-tools::profiling"]
description = "Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation."
edition = "2021"
keywords = ["cli", "load-testing", "performance", "http"]
license = "MIT"
name = "oha"
readme = "README.md"
repository = "https://github.com/hatoo/oha"
version = "0.5.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["native-tls"]
native-tls = ["dep:native-tls", "dep:tokio-native-tls"]
rustls = ["dep:rustls", "dep:tokio-rustls", "dep:rustls-native-certs"]

[dependencies]
anyhow = "1.0.38"
average = "0.13.0"
byte-unit = "4.0.8"
clap = {version = "4.1.4", features = ["derive"]}
crossterm = "0.25.0"
float-ord = "0.3.1"
flume = "0.10"
futures = "0.3.12"
humantime = "2.0.0"
libc = "0.2.67"
serde = {version = "1.0.142", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0.16"
tokio = {version = "1.14.0", features = ["full"]}
tui = {version = "0.19.0", default-features = false, features = ["crossterm"]}

http = "0.2"
hyper = {version = "0.14.13", features = ["full"]}

# native-tls
native-tls = {version = "0.2.11", optional = true}
tokio-native-tls = {version = "0.3.0", optional = true}

# rustls
rustls = {version = "0.20.4", features = ["dangerous_configuration"], optional = true}
rustls-native-certs = {version = "0.6.2", optional = true}
tokio-rustls = {version = "0.23.3", optional = true}

base64 = "0.21.0"
lazy_static = "1.4.0"
rand = "0.8"
trust-dns-resolver = "0.22.0"

[target.'cfg(unix)'.dependencies]
rlimit = "0.9.0"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.5.0"

[dev-dependencies]
assert_cmd = "2.0.2"
bytes = "1.0"
get-port = "4.0.0"
http = "0.2"
lazy_static = "1.4.0"
warp = "0.3"
